/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module cla_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire [3:1] c;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire [3:0] g;
  wire [3:0] p;
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__nor2_1 _03_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and2_0 _04_ (
    .A(b[0]),
    .B(a[0]),
    .X(g[0])
  );
  sky130_fd_sc_hd__nor2_1 _05_ (
    .A(_00_),
    .B(g[0]),
    .Y(p[0])
  );
  sky130_fd_sc_hd__and2_0 _06_ (
    .A(b[1]),
    .B(a[1]),
    .X(g[1])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(b[1]),
    .B(a[1]),
    .X(p[1])
  );
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and2_0 _09_ (
    .A(b[2]),
    .B(a[2]),
    .X(g[2])
  );
  sky130_fd_sc_hd__nor2_1 _10_ (
    .A(_01_),
    .B(g[2]),
    .Y(p[2])
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(b[3]),
    .B(a[3]),
    .X(g[3])
  );
  sky130_fd_sc_hd__nor2_1 _12_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(g[3]),
    .B(_02_),
    .Y(p[3])
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(b[0]),
    .B(a[0]),
    .C(cin),
    .X(c[1])
  );
  sky130_fd_sc_hd__a21o_1 _15_ (
    .A1(p[1]),
    .A2(c[1]),
    .B1(g[1]),
    .X(c[2])
  );
  sky130_fd_sc_hd__a21o_1 _16_ (
    .A1(p[2]),
    .A2(c[2]),
    .B1(g[2]),
    .X(c[3])
  );
  sky130_fd_sc_hd__a21o_1 _17_ (
    .A1(p[3]),
    .A2(c[3]),
    .B1(g[3]),
    .X(cout)
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(cin),
    .B(p[0]),
    .X(sum[0])
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(p[1]),
    .B(c[1]),
    .X(sum[1])
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(p[2]),
    .B(c[2]),
    .X(sum[2])
  );
  sky130_fd_sc_hd__xor2_1 _21_ (
    .A(p[3]),
    .B(c[3]),
    .X(sum[3])
  );
endmodule

module cla_8bit(a, b, cin, sum, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire c4;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [7:0] sum;
  wire [7:0] sum;
  cla_4bit cla_high (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(c4),
    .cout(cout),
    .sum(sum[7:4])
  );
  cla_4bit cla_low (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(c4),
    .sum(sum[3:0])
  );
endmodule
