/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module kogge_stone_adder(A, B, Cin, Sum, Cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  wire [8:0] C;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [7:0] Sum;
  wire [7:0] Sum;
  wire [7:0] g0;
  wire [7:0] g1;
  wire [7:0] g3;
  wire [7:0] p0;
  wire [7:0] p1;
  wire [7:0] p3;
  sky130_fd_sc_hd__nor2_1 _022_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _023_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _024_ (
    .A(_011_),
    .Y(g0[0])
  );
  sky130_fd_sc_hd__nand2b_1 _025_ (
    .A_N(_010_),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _026_ (
    .A(_012_),
    .Y(p0[0])
  );
  sky130_fd_sc_hd__nand2_1 _027_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _028_ (
    .A(_013_),
    .Y(g0[1])
  );
  sky130_fd_sc_hd__xnor2_1 _029_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _030_ (
    .A(_014_),
    .Y(p0[1])
  );
  sky130_fd_sc_hd__nand2_1 _031_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _032_ (
    .A(_015_),
    .Y(g0[2])
  );
  sky130_fd_sc_hd__xnor2_1 _033_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _034_ (
    .A(_016_),
    .Y(p0[2])
  );
  sky130_fd_sc_hd__nand2_1 _035_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _036_ (
    .A(_017_),
    .Y(g0[3])
  );
  sky130_fd_sc_hd__xnor2_1 _037_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _038_ (
    .A(_018_),
    .Y(p0[3])
  );
  sky130_fd_sc_hd__nand2_1 _039_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _040_ (
    .A(_019_),
    .Y(g0[4])
  );
  sky130_fd_sc_hd__xnor2_1 _041_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _042_ (
    .A(_020_),
    .Y(p0[4])
  );
  sky130_fd_sc_hd__and2_0 _043_ (
    .A(B[5]),
    .B(A[5]),
    .X(g0[5])
  );
  sky130_fd_sc_hd__xnor2_1 _044_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _045_ (
    .A(_021_),
    .Y(p0[5])
  );
  sky130_fd_sc_hd__nand2_1 _046_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _047_ (
    .A(_000_),
    .Y(g0[6])
  );
  sky130_fd_sc_hd__xnor2_1 _048_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _049_ (
    .A(_001_),
    .Y(p0[6])
  );
  sky130_fd_sc_hd__nor2_1 _050_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and2_0 _051_ (
    .A(B[7]),
    .B(A[7]),
    .X(g0[7])
  );
  sky130_fd_sc_hd__nor2_1 _052_ (
    .A(_002_),
    .B(g0[7]),
    .Y(p0[7])
  );
  sky130_fd_sc_hd__nand2_1 _053_ (
    .A(Cin),
    .B(p0[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _054_ (
    .A(_011_),
    .B(_003_),
    .Y(C[1])
  );
  sky130_fd_sc_hd__nor2_1 _055_ (
    .A(_012_),
    .B(_014_),
    .Y(p1[1])
  );
  sky130_fd_sc_hd__o21ai_0 _056_ (
    .A1(_011_),
    .A2(_014_),
    .B1(_013_),
    .Y(g1[1])
  );
  sky130_fd_sc_hd__a21o_1 _057_ (
    .A1(Cin),
    .A2(p1[1]),
    .B1(g1[1]),
    .X(C[2])
  );
  sky130_fd_sc_hd__nor2_1 _058_ (
    .A(_014_),
    .B(_016_),
    .Y(p1[2])
  );
  sky130_fd_sc_hd__nor3_1 _059_ (
    .A(_012_),
    .B(_014_),
    .C(_016_),
    .Y(p3[2])
  );
  sky130_fd_sc_hd__o21ai_0 _060_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_015_),
    .Y(g1[2])
  );
  sky130_fd_sc_hd__a21o_1 _061_ (
    .A1(g0[0]),
    .A2(p1[2]),
    .B1(g1[2]),
    .X(g3[2])
  );
  sky130_fd_sc_hd__a21o_1 _062_ (
    .A1(Cin),
    .A2(p3[2]),
    .B1(g3[2]),
    .X(C[3])
  );
  sky130_fd_sc_hd__xnor2_1 _063_ (
    .A(Cin),
    .B(_012_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__xnor2_1 _064_ (
    .A(_014_),
    .B(C[1]),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _065_ (
    .A(_016_),
    .B(C[2]),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _066_ (
    .A(_018_),
    .B(C[3]),
    .Y(Sum[3])
  );
  sky130_fd_sc_hd__o21ai_0 _067_ (
    .A1(_015_),
    .A2(_018_),
    .B1(_017_),
    .Y(g1[3])
  );
  sky130_fd_sc_hd__nor2_1 _068_ (
    .A(_016_),
    .B(_018_),
    .Y(p1[3])
  );
  sky130_fd_sc_hd__a21o_1 _069_ (
    .A1(g1[1]),
    .A2(p1[3]),
    .B1(g1[3]),
    .X(g3[3])
  );
  sky130_fd_sc_hd__and3_1 _070_ (
    .A(p0[0]),
    .B(p0[1]),
    .C(p1[3]),
    .X(p3[3])
  );
  sky130_fd_sc_hd__a21o_1 _071_ (
    .A1(Cin),
    .A2(p3[3]),
    .B1(g3[3]),
    .X(C[4])
  );
  sky130_fd_sc_hd__xnor2_1 _072_ (
    .A(_020_),
    .B(C[4]),
    .Y(Sum[4])
  );
  sky130_fd_sc_hd__o21ai_0 _073_ (
    .A1(_017_),
    .A2(_020_),
    .B1(_019_),
    .Y(g1[4])
  );
  sky130_fd_sc_hd__nor2_1 _074_ (
    .A(_018_),
    .B(_020_),
    .Y(p1[4])
  );
  sky130_fd_sc_hd__a21o_1 _075_ (
    .A1(g3[2]),
    .A2(p1[4]),
    .B1(g1[4]),
    .X(g3[4])
  );
  sky130_fd_sc_hd__and3_1 _076_ (
    .A(p0[0]),
    .B(p1[2]),
    .C(p1[4]),
    .X(p3[4])
  );
  sky130_fd_sc_hd__a21o_1 _077_ (
    .A1(Cin),
    .A2(p3[4]),
    .B1(g3[4]),
    .X(C[5])
  );
  sky130_fd_sc_hd__xnor2_1 _078_ (
    .A(_021_),
    .B(C[5]),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__a21oi_1 _079_ (
    .A1(g0[4]),
    .A2(p0[5]),
    .B1(g0[5]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _080_ (
    .A(_004_),
    .Y(g1[5])
  );
  sky130_fd_sc_hd__nor2_1 _081_ (
    .A(_020_),
    .B(_021_),
    .Y(p1[5])
  );
  sky130_fd_sc_hd__nand3_1 _082_ (
    .A(g1[1]),
    .B(p1[3]),
    .C(p1[5]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _083_ (
    .A(g1[3]),
    .B(p1[5]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand3_1 _084_ (
    .A(_004_),
    .B(_005_),
    .C(_006_),
    .Y(g3[5])
  );
  sky130_fd_sc_hd__and3_1 _085_ (
    .A(p1[1]),
    .B(p1[3]),
    .C(p1[5]),
    .X(p3[5])
  );
  sky130_fd_sc_hd__a21o_1 _086_ (
    .A1(Cin),
    .A2(p3[5]),
    .B1(g3[5]),
    .X(C[6])
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_001_),
    .B(C[6]),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__nand2_1 _088_ (
    .A(g0[5]),
    .B(p0[6]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _089_ (
    .A(_000_),
    .B(_007_),
    .Y(g1[6])
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(_021_),
    .B(_001_),
    .Y(p1[6])
  );
  sky130_fd_sc_hd__a21o_1 _091_ (
    .A1(g3[4]),
    .A2(p1[6]),
    .B1(g1[6]),
    .X(g3[6])
  );
  sky130_fd_sc_hd__and3_1 _092_ (
    .A(p3[2]),
    .B(p1[4]),
    .C(p1[6]),
    .X(p3[6])
  );
  sky130_fd_sc_hd__a221o_1 _093_ (
    .A1(g3[4]),
    .A2(p1[6]),
    .B1(p3[6]),
    .B2(Cin),
    .C1(g1[6]),
    .X(C[7])
  );
  sky130_fd_sc_hd__xor2_1 _094_ (
    .A(p0[7]),
    .B(C[7]),
    .X(Sum[7])
  );
  sky130_fd_sc_hd__nand2_1 _095_ (
    .A(p0[6]),
    .B(p0[7]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _096_ (
    .A(_008_),
    .Y(p1[7])
  );
  sky130_fd_sc_hd__o21bai_1 _097_ (
    .A1(_000_),
    .A2(_002_),
    .B1_N(g0[7]),
    .Y(g1[7])
  );
  sky130_fd_sc_hd__and3_1 _098_ (
    .A(p3[3]),
    .B(p1[5]),
    .C(p1[7]),
    .X(p3[7])
  );
  sky130_fd_sc_hd__o21bai_1 _099_ (
    .A1(_004_),
    .A2(_008_),
    .B1_N(g1[7]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a31o_1 _100_ (
    .A1(g3[3]),
    .A2(p1[5]),
    .A3(p1[7]),
    .B1(_009_),
    .X(g3[7])
  );
  sky130_fd_sc_hd__a21o_1 _101_ (
    .A1(Cin),
    .A2(p3[7]),
    .B1(g3[7]),
    .X(Cout)
  );
  assign { C[8], C[0] } = { Cout, Cin };
  assign g1[0] = g0[0];
  assign g3[1:0] = { g1[1], g0[0] };
  assign p1[0] = p0[0];
  assign p3[1:0] = { p1[1], p0[0] };
endmodule
