/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module ripple_adder(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [7:0] Sum;
  wire [7:0] Sum;
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(B[0]),
    .B(Cin),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(A[0]),
    .B(_00_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__or2_0 _22_ (
    .A(B[1]),
    .B(A[1]),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _23_ (
    .A(B[1]),
    .B(A[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _26_ (
    .A(B[0]),
    .B(A[0]),
    .C(Cin),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a22o_1 _28_ (
    .A1(_04_),
    .A2(_05_),
    .B1(_06_),
    .B2(_01_),
    .X(Sum[1])
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _30_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2b_1 _31_ (
    .A(_07_),
    .B_N(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _32_ (
    .A1(_02_),
    .A2(_05_),
    .B1(_01_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o22ai_1 _34_ (
    .A1(_09_),
    .A2(_10_),
    .B1(_11_),
    .B2(_07_),
    .Y(Sum[2])
  );
  sky130_fd_sc_hd__a21oi_1 _35_ (
    .A1(_08_),
    .A2(_10_),
    .B1(_07_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor3_1 _36_ (
    .A(B[3]),
    .B(A[3]),
    .C(_12_),
    .X(Sum[3])
  );
  sky130_fd_sc_hd__maj3_1 _37_ (
    .A(B[3]),
    .B(A[3]),
    .C(_12_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xor3_1 _38_ (
    .A(B[4]),
    .B(A[4]),
    .C(_13_),
    .X(Sum[4])
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(B[4]),
    .B(A[4]),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_14_),
    .B(_15_),
    .Y(Sum[5])
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(B[5]),
    .B(A[5]),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_16_),
    .B(_17_),
    .Y(Sum[6])
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(B[7]),
    .B(A[7]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__maj3_1 _46_ (
    .A(B[6]),
    .B(A[6]),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_18_),
    .B(_19_),
    .Y(Sum[7])
  );
  sky130_fd_sc_hd__maj3_1 _48_ (
    .A(B[7]),
    .B(A[7]),
    .C(_19_),
    .X(Cout)
  );
endmodule
